apiVersion: v1
kind: Service
metadata:
  name: {{ include "zootube.fullname" . }}-{{ .Values.api.component }}
  labels:
    {{- include "zootube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "zootube.selectorLabels" . | nindent 4 }}
    component: {{ .Values.api.component }}
