apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zootube.fullname" . }}-{{ .Values.api.component }}
  labels:
    {{- include "zootube.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "zootube.selectorLabels" . | nindent 6 }}
      component: {{ .Values.api.component }}
  template:
    metadata:
      labels:
        {{- include "zootube.selectorLabels" . | nindent 8 }}
        component: {{ .Values.api.component }}
    spec:
      containers:
      - name: {{ .Values.api.component }}
        image: {{ .Values.images.api.repository }}:{{ .Values.images.api.tag | default "latest" }}
        imagePullPolicy: {{ .Values.images.api.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        {{- if .Values.api.resources }}
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
        {{- end }}