apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zootube.fullname" . }}-{{ .Values.postgres.component }}-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.config.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.config.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.config.db | b64enc }}