apiVersion: v1
kind: Service
metadata:
  name: {{ include "zootube.fullname" . }}-{{ .Values.ui.component }}
  labels:
    {{- include "zootube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: 80
      protocol: TCP
      name: ui
  selector:
    {{- include "zootube.selectorLabels" . | nindent 4 }}
    component: {{ .Values.ui.component }}
